### ISSUE TITLE
O3653-9 MS login Bad Request

### ISSUE THREAD

**Issue by lucas66** [OfficeDev/hands-on-labs#94]
Module Number: O3653-9
Module Title: Microsoft Graph to connect to groups, add a member, see the group files and conversations
Path of file:
### Details of issue

Bad request when trying to login with BuildChallenge credentials.  See issue #93

**Comment by jasonjoh** [comment]
You still reproduce this? If so, can you email me offline the credentials? I don't have them.

**Comment by jthake** [comment]
The credentials would have changed, as the system rolls over every 4 hours. These are the standard Microsoft OFfice Demo tenants that we had created.

**Comment by jasonjoh** [comment]
Lucas sent me credentials, and I don't think these guys are admins.

```
Additional technical information: 
Correlation ID: 1be77426-5261-41dd-9bd7-e650608a4e82 
Timestamp: 2016-03-28 20:18:11Z 
AADSTS90093: Calling principal cannot consent due to lack of permissions. 
```

That error indicates they aren't. I logged into OWA and I don't see any admin option in the app launcher:

![image](https://cloud.githubusercontent.com/assets/8966342/14089139/49f4d068-f501-11e5-868c-ad6b0a251d59.png)

Contrast with a working admin user:

![image](https://cloud.githubusercontent.com/assets/8966342/14089164/765d166a-f501-11e5-8818-be0af35622c7.png)


The instructions say you should login with your admin account.

**Comment by jasonjoh** [comment]
After investigating with @jthake  and @richdizz, looks like the BuildChallenge creds are sometimes not giving you admins. This lab requires admins, so that needs fixing.

**Comment by jthake** [comment]
Can you confirm @lucas66 that this owrks if the tenant user is an administrator?

**Comment by jakubcech** [comment]
I'm posting here because I'm not sure if these are related, but it may be a separate issue:

Are we supposed to generate new tenants every time I want to get new ones at: https://tryoffice.azurewebsites.net/Home/GetAccount ? (using the same O365 account)

Because I'm getting the ones I generated when I requested them the first time and they're now long expired (can someone verify he gets the same?). I then get the same error as posted here, but this issue is probably non-admin user instead as you pointed out.

If the tenants aren't being re-generated, is it probable that attendants come back after their tenants have expired (to try different labs for example) and try to get new ones but get the expired tenants instead?

**Comment by lucas66** [comment]
@jakubcech I am getting the same credentials with an expiration date already past.  I generated these this morning.


Account 1

Username: brianj@dxdev03.onmicrosoft.com
Password: DOn@dUE9
Expires: 3/25/2016 9:41:33 PM
Account 2

Username: karif@dxdev03.onmicrosoft.com
Password: DOn@dUE9
Expires: 3/25/2016 9:41:31 PM
